<!-- START NOO WRAPPER -->
		<div class="noo-wrapper">
		  <!-- START MAINBODY -->
		  <div class="container noo-mainbody">
		  
		  <div>
		  
		  <p><h2>Terms of Use &amp; Privacy Policy</h2><br>   Please read these Terms of Use and Privacy Policy before using www.housesforsaletorent.co.uk (our &ldquo;Site&rdquo;) and any services, features, content or Apps (collectively referred to as &ldquo;Services&rdquo;) offered by Houses for Sale &amp; to Rent (&quot;we&quot;, &quot;us&quot; or &quot;our&quot;).</p>

<p>These Terms of Use set forth the legally binding terms and conditions for your use of the Site and our Services. You are allowed to use our Services only if you are in compliance with our Terms of Use, Privacy Policy and all applicable laws.</p>

<p>The following terms and conditions apply to everyone who uses Houses for Sale &amp; to Rent&rsquo;s Services, and they govern the relationship between Houses for Sale &amp; to Rent and our users during their use of our Services. By accessing and using our Services, you explicitly agree to comply with and be bound by our Terms of Use.</p>

<p>These terms and conditions are deemed to include our Privacy Policy and are collectively known as the &ldquo;Terms of Use&rdquo; or &ldquo;Terms&rdquo;.</p>

<p>When you use this Site, you agree to be bound by these Terms. Please read these Terms carefully before you start to use our Site. If you do not agree to be bound by these Terms, you must not use this Site. A reference to &quot;you&quot; or &quot;your&quot; is a reference to the user of this Site.</p>

<p>Certain uses of this Site are prohibited and amount to a misuse of our systems and the Site. We may change these Terms at our discretion by updating them on the Site. The then current version of these Terms will apply whenever you use this Site. Please check this page from time to time and take notice of any changes.</p>

<p>The copyright and all other intellectual property rights in this Site (including all database rights, trademarks, service marks, trading names, text, graphics, code, files and links) belong to us. All rights are reserved. You may download material from this Site for the sole purpose of using this Site. However, you must not copy, transmit, modify, republish, store (in whole or in part), frame, pass-off or link to any material or information on or downloaded from this Site without our prior written consent.</p>

<p>The Logo and the word mark &quot;Houses for Sale &amp; to Rent&quot; are ours. You must not use or copy them without our prior written consent.</p>

<p>This Site also contains links to websites operated by third parties. We have no control over their individual content. We therefore make no warranties or representations as to the accuracy or completeness of any of the information appearing in relation to any linked websites. The links are for your convenience only. We do not recommend any products or services advertised on those websites. If you decide to access any third party website linked from this Site, you do so at your own risk.</p>

<p>We are not an estate agency. The details of the properties available on this Site are provided to us by third parties, landlords or developers for your information only. We do not verify the property details provided to us and therefore make no warranties or representations as to their accuracy or completeness. If you rely on these details, you do so at your own risk. We recommend that you check all property details with the advertising estate agent, landlord, property portal or developer before making any decisions or taking any action in regards to a property advertised on our Site. You accept that you are solely responsible for ensuring that your computer system meets all relevant technical specification necessary to use this Site and that your computer system is compatible with this Site. You must not misuse our system or this Site. In particular, you must not hack into, circumvent security or otherwise disrupt the operation of our system and this Site, or attempt to carry out any of the foregoing. This includes introducing viruses, trojans, worms, logic bombs or other material which is or could be malicious or technologically harmful.</p>

<p>You must not use or attempt to use any automated program (including, without limitation, any spider or other web crawler) to access our system or this Site, or to search, display or obtain links to any part of this Site, other than the home page at www.housesforsaletorent.co.uk unless the automated program identifies itself uniquely in the User Agent field and is fully compliant with the Robots Exclusion Protocol (a &quot;Permitted Program&quot;). Any such use or attempted use of an automated program (other than a Permitted Program) shall be a misuse of our system and this Site. Obtaining access to any part of our system or this Site by means of any such automated programs (other than a Permitted Program) is strictly unauthorised.</p>

<p>You must not include links to this Site in any other Site without our prior written consent. In particular (but without limiting the foregoing) you must not include in any other Site any &quot;deep link&quot; to any page on this Site. You may link to our home page at www.housesforsaletorent.co.uk provided that you do so in a way that does not (in our reasonable opinion) damage our reputation or expose us to risk. We reserve the right to withdraw linking permission without notice and without giving a reason.</p>

<p>You must not upload or use inappropriate or offensive language or content or solicit any commercial services in any communication, form or e-mail you send or submit, from or to the Site. Whenever you make use of features that allow you to upload content to our Site, or to make contact with other users via our Site, you must comply with the content standards set out in these Terms. You warrant that any such contribution does comply with the standards mentioned and you will be liable to us and indemnify us against any breach of this warranty.</p>

<p>All content that you upload to our Site will be considered non-confidential and non-proprietary and we have the right to use, copy, distribute and disclose to third parties any such content for any purpose without any royalty or fees. We also have the right to disclose your identity to any third party who claims or alleges that content posted or uploaded by you to our Site breaches that third party&rsquo;s legal rights.</p>

<p>You are solely responsible for your Content, which once published, cannot be always withdrawn or taken down. You also assume all risks associated with your content, including anyone's reliance on its quality, accuracy or reliability or any disclosure by you of information in Your Content that makes you personally identifiable. The views expressed by users on our Site do not represent our views or values and we will not be held responsible for them in any way.</p>

<p>All content that you upload to our Site must:   Be factually accurate Be genuinely held (where you state opinions); and Comply with the applicable law of the country from which they were posted. Your content must not:   Contain any material which is defamatory of any person; Contain any material which is obscene, offensive, hateful, discriminatory, unethical, immoral or inflammatory; or Contain any material which does or could potentially infringe the intellectual property rights of a third party. We will determine in our discretion whether there has been a breach of this. Where a breach of this policy has occurred we may take such action as we deem appropriate. This action may include the following:   Immediate, temporary or permanent withdrawal of your right to use our Site; Immediate, temporary or permanent removal of any posting or material uploaded by you to our Site; Further legal action against you; and Disclosure of such information to law enforcement or authorities as we reasonably feel necessary. In addition to all of our rights set out above, we reserve the right to take down any content that you upload to our Site at any time without notice and without having to give a reason.</p>

<p>To receive details of properties on this Site, you must submit a completed registration form to us. At our discretion, we may refuse your application for registration. If we accept your application for registration, we will confirm this by sending you an e-mail containing your account ID.</p>

<p>Each registration is for a single user only. You must not share your username and password with any other person or with multiple users on a network.</p>

<p>You must be over eighteen years of age to register on our website and must ensure that the details provided by you on registration are true, accurate, current and complete.</p>

<p>By registering with the service, you agree that we can send you emails about your account, other Houses for Sale &amp; to Rent services and occasional third party offers.</p>

<p>You accept sole responsibility for all use of and for keeping secret any account ID and password that may have been given to you or chosen by you for use on this Site. You will notify us immediately of any unauthorised use of them or any other breach of security of this Site of which you become aware.</p>

<p>We reserve the right to bar users from this Site and/or restrict or disable their access or use of any or all elements of our services, on a permanent or temporary basis at our sole discretion. Any such user shall be notified and must not then attempt to use this Site under any other name or through any other user.</p>

<p>Whilst we endeavour to ensure that any material available for downloading from this Site is not contaminated in any way, we do not warrant that such material will be free from infection, viruses and/or similar code. Due to the nature of software and the internet, we do not warrant that your access to, or the running of, this Site will be uninterrupted or error free. We may suspend, withdraw, discontinue or change all or any part of our Site without notice. </p>

<p>We shall not be liable if we cannot process your details due to circumstances beyond our reasonable control. The information provided on this Site is for general interest only and does not constitute specific advice. We make no warranties or representations that the property information on this Site is correct, accurate or up-to-date. We make no warranty or guarantee that the Site or information available over it complies with laws other than those of England.</p>

<p>To the extent permitted by law, we exclude all conditions, warranties, representations or other terms which may apply to our Site or any content on it, whether express or implied. Nothing in these Terms will be deemed to exclude our liability to you for death or personal injury arising from our negligence, or for fraudulent misrepresentation.</p>

<p>We will not be liable for any failures due to software or Internet errors or unavailability, or any other circumstances beyond our reasonable control.</p>

<p>We do not accept any liability for loss of your password or account ID caused by a breakdown, error, loss of power or otherwise caused by or to your computer system.</p>

<p>We may put in place such systems as we from time to time see fit to prevent automated programs being used to obtain unauthorised access to our system and this Site. You are not permitted to use automated programs for such purposes and any such use or attempted use by you of such automated programs is at your own risk. We shall not be liable to you for any consequences arising out of or in connection with any such use or attempted use of automated programs to obtain unauthorised access to our system or this Site.</p>

<p>We will not be liable to you for any loss or damage, whether in contract, tort (including negligence), breach of statutory duty or otherwise, even if foreseeable, arising under or in connection with:   Use of, or inability to use, our Site; or Use of or reliance on any content or information displayed on our Site. If you are a business we shall not be liable to you for:   Any indirect, consequential, special or punitive loss, damage, costs and expenses; loss of profit; loss of business; loss of reputation; depletion of goodwill; or loss of, damage to or corruption of data.</p>

<p>If you are a consumer, please note that we only provide our Site for domestic and private use. You agree not to use our Site for any commercial or business purposes and we have no liability to you for any loss of profit, loss of business, business interruption or loss of business opportunity.</p>

<p>We will not be liable for any loss or damage caused by a virus, distributed denial of service attack or other technologically harmful material that may infect your computer equipment, computer programmes, data or other proprietary material due to your use of our Site or to your downloading of any content on it, or any website linked to it.</p>

<p>When you use the &quot;contact forms&quot; on this Site to enquire about a property, your details (including your e-mail address) will be sent by e-mail directly to the estate agent, landlord or developer marketing the property or properties that you are enquiring about. We do not accept any liability for any subsequent communications that you receive directly from other users or third parties.</p>

<p>All notices shall be given to us, by e-mail at info@housesforsaletorent.co.uk. If you have registered to use our services then we may serve a notice on you by email at the email address provided to us at the point of registration.</p>

<p>All notices sent by email will be deemed to have been received on the day that they are sent or, if sent on a national holiday in England or on a Saturday or Sunday, the next working day following the day on which the email was sent. We may from time to time change the content of this Site or suspend or discontinue any aspect of this Site, which may include your access to it. Any amendments to these Terms will be made available. We may revise these Terms at any time by amending this page. Please check this page from time to time to take notice of any changes we made, as they are binding on you.</p>

<p>If you are a business user, these Terms are the whole agreement between you and us. You acknowledge that you have not entered into this agreement in reliance on any warranty or representation made by us (unless made fraudulently). If a court decides that any part of these Terms cannot be enforced, that particular part of these Terms will not apply, but the rest of these Terms will. A waiver by a party of a breach of any provision shall not be deemed a continuing waiver or a waiver of any subsequent breach of the same or any other provisions. Failure or delay in exercising any right under these Terms shall not prevent the exercise of that or any other right. You may not assign or transfer any benefit, interest or obligation under these Terms. The provisions of the Contracts (Rights of Third Parties) Act 1999 shall not apply to these Terms.</p>

<p>If you are a consumer user, please note that these Terms and their subject matter and formation (including any non-contractual dispute or claim) are governed by English Law. You and we both agree that the courts of England and Wales will have non-exclusive jurisdiction. However, if you are a resident of Northern Ireland you may also bring proceedings in Northern Ireland, and if you are a resident in Scotland, you may also bring proceedings in Scotland. If you are a business user, these Terms and their subject matter and formation (including any non-contractual disputes or claims) are governed by English law and will be subject to the exclusive jurisdiction of the English courts. To contact us, please e-mail at info@housesforsaletorent.co.uk or send post to our address shown at the beginning of these Terms.</p>

<p>Privacy Policy: We are dedicated to keeping your privacy. This Privacy Policy details the policies of www.housesforsaletorent.co.uk (&ldquo;Houses for Sale &amp; to Rent&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo; or &ldquo;our&rdquo;) on the gathering, usage and disclosure of your information on www.housesforsaletorent.co.uk (referred to as our &quot;Site&quot;) and the services, features, content or apps we offer (jointly referred to as &quot;Services&quot;). When you use our Services, you are agreeing to the gathering, transfer, management, storage, disclosure and other uses of your information as defined in this Privacy Policy. This policy gives information about cookies; how we use cookies; and how you may deactivate cookies. This policy does not apply to the practices of companies and sites that we do not own or control, or to people that we do not employ or manage.</p>

<p>Our Privacy Policy is incorporated as part of the Houses for Sale &amp; to Rent Terms of Use. Please read this Policy and our Terms carefully before using our Services. If you do not want to be bound by our Privacy Policy, please refrain from using our Services.</p>

<p>Our Privacy Policy covers the management of personally identifiable information (referred to as &ldquo;Personal Information&rdquo;) collected when you use or access our Site. This Privacy Policy also covers our treatment of any Personal Information which landlords, tenants or our business associates share with us, or that we share with our business partners and associates.</p>

<p>This Privacy Policy does not cover the practices or actions of third parties that we do not own or control, including but not limited to any landlords, tenants, third party websites, services and apps (referred to as &ldquo;Third Party Services&rdquo;) that you choose to access through the Services or to individuals that we do not manage or employ. While we attempt to facilitate access only to those Third Party Services that share our respect for your privacy or that you request through your use of the Services, we cannot take responsibility for the content or privacy policies of those Third Party Services. We encourage you to carefully review the privacy policies of any Third Party Services you access.</p>

<p>Houses for Sale &amp; to Rent is a property search engine. In order to provide our services, we do use information we gather in order to help you find the most relevant information you are looking for. We do customise our services to optimise and improve your user experience.</p>

<p>We keep you connected with Houses for Sale &amp; to Rent on the Internet and update you with residential and property-related news and information, if you allow us to do so. We intend to put you in touch with the right people to sell, buy, rent, or research property, obtain a mortgage, and to optimise the information we share with those parties to initiate a productive and efficient relationship.</p>

<p>Our goal in this policy is to be completely transparent about the data we collect, why we collect it, and how we use it, in order to make finding your new home a pleasant and memorable experience. Your information may be maintained on and transferred to computers located outside your state, province, country or any jurisdiction. If you are located outside the United Kingdom and choose to use our Services, the information we gather will be transferred to the United Kingdom before processing. Your use of our Services and submission of any information represents your consent to such transfer.</p>

<p>When you choose to use our Services we collect a variety of information including: Information you provide. When using our Services, you may provide information about yourself, such as name, address, phone number, e-mail and details around a potential transaction. This may occur, for example, when you register on Houses for Sale &amp; to Rent or complete other forms. You may also provide information about a third party through the Services, for example, if you share a listing with a recipient via email. We may combine this information with other information we collect from your interaction and use of our Services or from other companies. We also automatically receive and record information in our server logs from your browser, including your IP address, search queries, cookie information, and the listings and pages you request. We also record the details of your activity on the Services.</p>

<p>Information collected using cookies. Cookies are pieces of text that may be provided to your computer through your web browser when you access a website. Your browser stores cookies in a manner associated with each website you visit. We use cookies to enable our servers to recognise your web browser and tell us how and when you visit the Site and otherwise use the Services through the Internet. Our cookies do not, by themselves, contain Personal Information, and we do not combine the general information collected through cookies with other Personal Information to tell us who you are. As noted, however, we do use cookies to identify that your web browser has accessed aspects of the Services. Most browsers have an option for turning off the cookie feature, which will prevent your browser from accepting new cookies, as well as (depending on the sophistication of your browser software) allowing you to decide on acceptance of each new cookie in a variety of ways.</p>

<p>However, if you choose to disable cookies, many of the free features and Services on Houses for Sale &amp; to Rent may not operate appropriately. Also, the pages on the Services may include Web beacons, which are electronic files to count users who have visited that page, to identify certain cookies on the computer or other electronic device accessing that page, or to collect other related information.</p>

<p>This Privacy Policy covers our use of cookies only and does not cover the use of cookies by third parties, including our partners. We do not control when or how third parties place cookies on your computer. Third party websites to which a link points may set cookies on your computer. Ads appearing on the Services may be delivered to users by our advertising partners, who may set cookies. These cookies allow the ad server to recognise your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This Privacy Policy covers the use of cookies by Houses for Sale &amp; to Rent and does not cover the use of cookies by any third parties, including advertisers or partners.   Information collected from Mobile Browsers. You can easily adjust the settings on your mobile device and mobile browser regarding cookies and sharing of certain information, such as your mobile device model or the language your mobile device uses, by adjusting the privacy and security settings on your mobile device. Please refer to the instructions provided by your mobile service provider or mobile device manufacturer in order to do so.   Information collected from Social Networks. If you use the social networking connection functions offered through our Services, we may access all of your social network profile information that you have made available to be shared and to use it in accordance with this privacy policy. Please refer to the instructions governing your social network account to manage the information that is shared through your account.</p>

<p>Information collected from your interaction with our Services. We collect statistical information about how users collectively interact with our Services. Some of this information is derived from Personal Information. This statistical information is not Personal Information and cannot be tied back to you or your web browser. This type of aggregate data enables us to figure out how often users use parts of the Services so that we can make the Services appealing to as many users as possible, and improve them. As part of this use of information, we may provide aggregate information to our partners about how our users, collectively, use our site. We share this type of statistical data so that our partners also understand how often people use their services and our Services, so that they, too, may provide you with an optimal online experience.</p>

<p>We also use conversion tracking from third-party advertising platforms, including Google and Facebook. These advertising programs use cookies to help determine aggregate, anonymous actions people took on our website after clicking an ad. You need to prevent unauthorised access to your account and Personal Information by selecting and protecting your password appropriately and limiting access to your computer and browser by signing off after you have finished accessing your account. We endeavour to protect account information to ensure that it is kept private; however, we cannot guarantee the security of any account information. unauthorised entry or use, hardware or software failure, and other factors, may compromise the security of user information at any time. We otherwise store all of our information, including your IP address information, using industry-standard security techniques. We do not guarantee or warrant that such techniques will prevent unauthorised access to information about you we store, Personal Information or otherwise.</p>

<p>E-mail Communication from Us and other users. As part of our Services, you may occasionally receive email and other communications from us, such as communications relating to promotions we are offering through or related to our Services. You acknowledge and agree that by posting information on our site or through using our services, or requesting that we do so on your behalf, we and others may send you e-mail, contact you or engage in other communications at our sole discretion.</p>

<p>You may opt-out of receiving such communications by following the instructions included with such emails, or emailing us at info@housesforsaletorent.co.uk, but then you may not have access to certain features of our Services. In addition, we and others you interact with through the Services may wish to send you an e-mail, and you acknowledge and agree that we may share your Personal Information with such persons, or use your Personal Information for such purposes.   Information shared with our associates. We employ and contract with people and other entities (referred to as our &ldquo;Associates&rdquo;) that perform certain tasks on our behalf and who are under our control. We may need to share Personal Information with our Associates in order to provide Services to you. Unless we tell you differently, our Associates do not have any right to use Personal Information or other information we share with them beyond what is necessary to assist us. You hereby consent to our sharing of Personal Information with our Associates.   Information disclosed pursuant to Business mergers, sales and acquisitions. In some cases, we may choose to buy or sell assets. In these types of transactions, user information is typically one of the transferred business assets. Moreover, if we, or substantially all of our assets, were acquired, or if we go out of business or enter bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of us or our assets may continue to use your Personal Information as set forth in this policy.   Information disclosed for our protection and the protection of others. We also reserve the right to access, read, preserve, and disclose any information as we reasonably believe is necessary to (i) satisfy any applicable law, regulation, legal process or governmental request, (ii) enforce the Terms of Use or this Privacy Policy, including investigation of potential violations thereof or hereof, (iii) detect, prevent, or otherwise address fraud, security or technical issues, (iv) respond to user support requests, or (v) protect our rights, property or safety, our users and the public. This includes exchanging information with other companies and organisations for fraud protection and spam/malware prevention.   Information we share in connection with the Services performed for you. The information you provide, including, without limitation, your profile information, search criteria, user name, e-mail, address, may be used to facilitate and provide the services for you and transactions within our Services. This may include, without limitation, sharing your Personal Information with potential landlords, brokers, co-brokers, as applicable to your request for Services; and if you are landlord, we may also share your Personal Information (such as name, listing address, etc.) to potential tenants in connection with the Services.</p>

<p>Information we Share with your consent. Except as set forth above, you will be notified when your Personal Information may be shared with third parties, and will be able to prevent the sharing of this information. We may allow you to access certain information about you for the purpose of viewing, and in certain situations, updating that information. This list will change as our Services change. When you update information, however, we often maintain a copy of the unrevised information in our records. You may request deletion of your account by sending an e-mail to our webmaster at info@housesforsaletorent.co.uk. Please note that some information may remain in our records even after deletion of your account.</p>

<p>We may amend this Privacy Policy from time to time. Use of information we collect now is subject to the Privacy Policy in effect at the time such information is used. If we make changes in the way we collect or use information, this document will be updated. A user is bound by any changes to the Privacy Policy when he or she uses the Services after such changes have been first updated. If you have any questions or concerns regarding privacy using our Services, please send us a detailed e-mail to info@housesforsaletorent.co.uk. We will make every effort to resolve your concerns and answer any questions.   Terms of Use and Privacy Policy last updated: 06/08/2015</p>
		  
		  </div>
		  
		  
		  
		  
		  
		  
		  
		  </div>
      <!-- END MAINBODY -->
    </div>
    <!-- END NOO WRAPPER -->